<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLySanPham" Class="CSDLQuanLyQuanAoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=QUY\QUY;Initial Catalog=QuanLySanPham;Persist Security Info=True;User ID=sa" SettingsObjectName="QuanLyQuanAo.Properties.Settings" SettingsPropertyName="QuanLySanPhamConnectionString2" Provider="System.Data.SqlClient" />
</Database>