//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanAo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=quanlyquanao.database.windows.net;Initial Catalog=QuanLyQuanAo;Persis" +
            "t Security Info=True;User ID=ThanhQuy")]
        public string QuanLyQuanAoConnectionString {
            get {
                return ((string)(this["QuanLyQuanAoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=quanlyquanao.database.windows.net;Initial Catalog=QuanLyQuanAo;Persis" +
            "t Security Info=True;User ID=ThanhQuy;Password=Quy0164vn")]
        public string QuanLyQuanAoConnectionString1 {
            get {
                return ((string)(this["QuanLyQuanAoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=quanlyquanao.database.windows.net;Initial Catalog=QuanLySanPham;Persi" +
            "st Security Info=True;User ID=ThanhQuy;Password=Quy0164vn")]
        public string QuanLySanPhamConnectionString {
            get {
                return ((string)(this["QuanLySanPhamConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.87.155.205;Initial Catalog=QuanLySanPham;Persist Security Info=Tru" +
            "e;User ID=sqlserver;Password=113114115")]
        public string QuanLySanPhamConnectionString1 {
            get {
                return ((string)(this["QuanLySanPhamConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=QUY\\QUY;Initial Catalog=QuanLySanPham;Persist Security Info=True;User" +
            " ID=sa;Password=Quy0164vn")]
        public string QuanLySanPhamConnectionString2 {
            get {
                return ((string)(this["QuanLySanPhamConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.87.7.251;Initial Catalog=QuanLySanPham;Persist Security Info=True;" +
            "User ID=sqlserver;Password=113114115")]
        public string QuanLySanPhamConnectionString3 {
            get {
                return ((string)(this["QuanLySanPhamConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U8PDCCC;Initial Catalog=QuanLySanPham;Persist Security Info=T" +
            "rue;User ID=lecongtuan;Password=koqata08081999")]
        public string QuanLySanPhamConnectionString4 {
            get {
                return ((string)(this["QuanLySanPhamConnectionString4"]));
            }
        }
    }
}
